title: Sebastian Henao-Garcia
logo: /assets/img/profile_picture.jpg
description: Computational modeling, wind energy, and sustainability enthusiast
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
